# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bootstrap_pb2 as bootstrap__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bootstrap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SidecarSessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.unary_stream(
                '/pole.sidecar.v1.SidecarSessionService/OpenSession',
                request_serializer=bootstrap__pb2.ClientHello.SerializeToString,
                response_deserializer=bootstrap__pb2.SidecarEvent.FromString,
                _registered_method=True)
        self.OpenControlSession = channel.stream_stream(
                '/pole.sidecar.v1.SidecarSessionService/OpenControlSession',
                request_serializer=bootstrap__pb2.ClientEvent.SerializeToString,
                response_deserializer=bootstrap__pb2.SidecarEvent.FromString,
                _registered_method=True)


class SidecarSessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request, context):
        """Legacy listener bootstrap retained for existing Thin SDKs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenControlSession(self, request_iterator, context):
        """Long-lived Thin SDK control session. The first ClientEvent must contain
        ClientHello. Registrations belong to this stream and are removed when it
        closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidecarSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=bootstrap__pb2.ClientHello.FromString,
                    response_serializer=bootstrap__pb2.SidecarEvent.SerializeToString,
            ),
            'OpenControlSession': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenControlSession,
                    request_deserializer=bootstrap__pb2.ClientEvent.FromString,
                    response_serializer=bootstrap__pb2.SidecarEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pole.sidecar.v1.SidecarSessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pole.sidecar.v1.SidecarSessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidecarSessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pole.sidecar.v1.SidecarSessionService/OpenSession',
            bootstrap__pb2.ClientHello.SerializeToString,
            bootstrap__pb2.SidecarEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
    @staticmethod
    def OpenControlSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pole.sidecar.v1.SidecarSessionService/OpenControlSession',
            bootstrap__pb2.ClientEvent.SerializeToString,
            bootstrap__pb2.SidecarEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
