# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import bootstrap_pb2 as bootstrap__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in bootstrap_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
    )


class SidecarSessionServiceStub:
    def __init__(self, channel):
        self.OpenSession = channel.unary_stream(
            "/pole.sidecar.v1.SidecarSessionService/OpenSession",
            request_serializer=bootstrap__pb2.ClientHello.SerializeToString,
            response_deserializer=bootstrap__pb2.SidecarEvent.FromString,
            _registered_method=True,
        )


class SidecarSessionServiceServicer:
    def OpenSession(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SidecarSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "OpenSession": grpc.unary_stream_rpc_method_handler(
            servicer.OpenSession,
            request_deserializer=bootstrap__pb2.ClientHello.FromString,
            response_serializer=bootstrap__pb2.SidecarEvent.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "pole.sidecar.v1.SidecarSessionService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "pole.sidecar.v1.SidecarSessionService", rpc_method_handlers
    )


class SidecarSessionService:
    @staticmethod
    def OpenSession(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/pole.sidecar.v1.SidecarSessionService/OpenSession",
            bootstrap__pb2.ClientHello.SerializeToString,
            bootstrap__pb2.SidecarEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
